### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Gluglo** [Polyfrost/Chatting#10]
I'm not sure what's happening to the screenshots I make with this mod, not even sure if they are being saved anywhere. Where could I find this or could you make it so that it saves the message screenshots in the future?

**Comment by Wyvest** [comment]
> I'm not sure what's happening to the screenshots I make with this mod, not even sure if they are being saved anywhere. Where could I find this or could you make it so that it saves the message screenshots in the future?

They should be saved in your Minecraft screenshots folder.

**Comment by Gluglo** [comment]
Ok thanks!

**Comment by Gluglo** [comment]
I just use a launcher for this mod so I didn't see it in minecraft ss, realized I had to check the launcher's ss after this lol
