### ISSUE TITLE
Wrong hoverstate with smooth chat messages

### ISSUE THREAD

**Issue by romangraef** [Polyfrost/Chatting#17]
![image](https://user-images.githubusercontent.com/20768569/212661303-4b1177a3-a6a0-40e5-a243-78ee2a82e6f3.png)
Prevents clicking on message actions and copying chat.

**Comment by Wyvest** [comment]
> ![image](https://user-images.githubusercontent.com/20768569/212661303-4b1177a3-a6a0-40e5-a243-78ee2a82e6f3.png)
> Prevents clicking on message actions and copying chat.

are you sure this is a thing with smooth chat messages or is it smooth scrolling

**Comment by Wyvest** [comment]
also i cant reproduce the issue with chatting + patcher

**Comment by Wyvest** [comment]
cannot reproduce, closing

**Comment by romangraef** [comment]
Oh yeah, me neither nowadays, not sure when or what fixed it
