### ISSUE TITLE
Licensing changes

### ISSUE THREAD

**Issue by Wyvest** [Polyfrost/Chatting#34]
The code in this repository currently has a license of "LGPL-3.0". Although great for libraries (such as OneConfig) where they may be used in proprietary projects, Polyfrost as an organization believes strongly in keeping our code free and open source to everyone; keeping our mods under the LGPL-3.0 leaves them vulnerable to malicious entities (e.g clients) simply ripping features from them. To protect our code from such usage and continue maintaining our code for no price, we would like to use a more copyleft license.

Hence, we want to relicense this repository, including your code, under a compatible license. The license we are choosing is version 3 of the GNU General Public License, ALONGSIDE the `"MINECRAFT" LINKING EXCEPTION TO THE GPL`, which is linked [here](https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt).

```
"MINECRAFT" LINKING EXCEPTION TO THE GPL

Linking this mod statically or dynamically with other modules is making a
combined work based on this mod. Thus, the terms and conditions of the GNU
General Public License cover the whole combination.

In addition, as a special exception, the copyright holders of this mod give you
permission to combine this mod with free software programs or libraries that
are released under the GNU LGPL and with code included in the standard release
of Minecraft under All Rights Reserved (or modified versions of such code, with
unchanged license). You may copy and distribute such a system following the
terms of the GNU GPL for this mod and the licenses of the other code concerned.

Note that people who make modified versions of this mod are not obligated to
grant this special exception for their modified versions; it is their choice
whether to do so. The GNU General Public License gives permission to release a
modified version without this exception; this exception also makes it possible
to release a modified version which carries forward this exception.
```

If you are mentioned below, we need your help to relicense this repository, as you are a copyright holder of your contributed code.

## Making it happen

To make it happen, please comment on this issue with the following:

`I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>`

## Contributor checklist

- [x] @ImToggle 
- [x] @RedthMC 
- [x] @DeDiamondPro 
- [x] @xthe-dev 
- [x] @KTibow 
- [x] @MicrocontrollersDev 
- [x] @ThatGravyBoat 
- [x] @Cephetir 
- [x] @pauliesnug 
- [x] @sinender 
- [x] @jacobk999 
- [x] @momenazhar 
- [x] @raeids 
- [x] @walkerselby 
- [x] @nextdayy 
- [x] @xtrm-en

**Comment by Wyvest** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by sinender** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by jacobk999** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by walkerselby** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by MicrocontrollersDev** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by momenazhar** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by ThatGravyBoat** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by Wyvest** [comment]
@sinender @jacobk999 @walkerselby @Cephetir @MicrocontrollersDev @momenazhar @ThatGravyBoat I made an oversight and forgot that GPL 3.0 is incompatible with Minecraft by default. Please read over the issue again, and comment accordingly. Apologies for the inconvenience.

**Comment by Wyvest** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by sinender** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by walkerselby** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by pauliesnug** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by ThatGravyBoat** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by momenazhar** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by MicrocontrollersDev** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by RedthMC** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by DeDiamondPro** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by Cephetir** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at https://www.gnu.org/licenses, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt and reproduced at #34

**Comment by xthe-dev** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by raeids** [comment]
I license past and future contributions under version 3 or (at your
option) any later version of the GNU General Public License, as published
by the Free Software Foundation at <https://www.gnu.org/licenses>

**Comment by raeids** [comment]
I license past and future contributions under version 3 or (at your
option) any later version of the GNU General Public License, as published
by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the
"MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <
https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt>
and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by xtrm-en** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by ImToggle** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by nextdayy** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by jacobk999** [comment]
I license past and future contributions under version 3 or (at your option) any later version of the GNU General Public License, as published by the Free Software Foundation at <https://www.gnu.org/licenses>, AND the "MINECRAFT" LINKING EXCEPTION TO THE GPL, as written in <https://gist.githubusercontent.com/Wyvest/9219cefc3e79f85a081826f9160e1c3a/raw/3a9b661bcb072e17eff7bfbecbdbdfb5f20e3db4/gistfile1.txt> and reproduced at <https://github.com/Polyfrost/Chatting/issues/34>

**Comment by Wyvest** [comment]
Thank you to everyone who helped! We've gotten all the comments we need and I am about to relicense this project to the GPL with the MC exception. Thank you!
