### ISSUE TITLE
Not compatible with Feather client

### ISSUE THREAD

**Issue by Kynz0** [Polyfrost/Chatting#37]
When you install this mod on the Feather client it doesn't work as intended:
![image](https://github.com/Polyfrost/Chatting/assets/90714597/f5457555-47b1-432f-b2a6-55b4d85f9b14)
The messages are viewed at the top of the screen instead of the chat box, although the tooltips of the messages seem to be in the right place.

I tried turning every feather module off and turning all the feather chat settings off but it doesn't seem to help, I think that some features of the feather chat settings can't me turned off and that's why this is happening.

Hope this is fixable on your part cus I'am not sure if feather would want to do something about it :D

**Comment by Wyvest** [comment]
Won't fix, Feather is not supported
